### PR TITLE
fix: use FileFunction.cached

### PR DESCRIPTION
**Pull request by regiskuckaertz**
hello 🤠 I have been investigating an issue in our pipeline that happens between our `build` stage where we generate sources and compile, and the `test` stage where we run tests. We are getting IO errors during the `test` stage that look like this:

```
sbt:hello-world> test
[info] compiling 12 Scala sources to /Users/regiskuckaertz/code/guard1/hw2/target/scala-2.13/classes ...
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/AkkaHttpImplicits.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/AkkaHttpImplicits.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/Client.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/Client.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/Implicits.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/Implicits.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/ApiResponse.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/ApiResponse.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Category.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Category.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Order.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Order.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Pet.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Pet.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Tag.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/Tag.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/User.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/User.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/package.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/definitions/package.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] IO error while decoding /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/support/Presence.scala with UTF-8: /Users/regiskuckaertz/code/guard1/hello-world/target/scala-2.13/src_managed/main/com/regiskuckaertz/support/Presence.scala (No such file or directory)
[error] Please try specifying another one using the -encoding option
[error] 11 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 10 Jun 2023, 18:46:11%                                                                                                                                                     
```

I noticed the paths listed in the errors were the absolute paths of the sources generated during the `compile` stage. Of course they don't exist anymore since the `build` stage runs in a separate runner with a different base directory. The only place I could think of where absolute paths would be persisted on disk was in the SBT caching (the `streams` task). It seems that something shady is happening with `Tracked.inputChanged`, as after replacing with `FileFunction.cached` I'm unable to reproduce the issue. To reproduce here is what I did:

- create a new sbt project under directory `hello1`, with an openapi spec, and a test using the generated code
- sbt clean compile
- exit the project
- rename `hello1` to `hello2`
- sbt test

That would fail consistently, but not anymore.

I also took the liberty of wrapping the task with a `try/finally` to make sure the classloader is restored in case an exception is thrown.

### CODE REVIEW

**Review by blast-hardcheese — APPROVED** [review]
Much simpler, very much appreciated!

**Comment by blast-hardcheese** [comment]
> I also took the liberty of wrapping the task with a try/finally to make sure the classloader is restored in case an exception is thrown.

I would have expected (hoped?) that that'd have been restored at the end of the Task (🙈)

either way, great to have

**Comment by blast-hardcheese** [comment]
https://github.com/guardrail-dev/sbt-guardrail/releases/tag/v0.75.2 has been cut!

**Comment by regiskuckaertz** [comment]
@blast-hardcheese Thanks heaps 🙏 have a great day

**Pull request merged**
